general.import = [ "~/.config/omarchy/current/theme/alacritty.toml" ]

[terminal]
shell = "/usr/bin/nu"

[env]
TERM = "xterm-256color"

[font]
# normal = { family = "JetBrainsMono Nerd Font" }
# bold = { family = "JetBrainsMono Nerd Font" }
# italic = { family = "JetBrainsMono Nerd Font" }
normal = { family = "Berkeley Mono" }
bold = { family = "Berkeley Mono" }
italic = { family = "Berkeley Mono" }
size = 16

[window]
padding.x = 14
padding.y = 14
decorations = "None"

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]
