"$schema" = 'https://starship.rs/config-schema.json'
add_newline = true
command_timeout = 200
format = "[$directory$git_branch$git_status$kubernetes$aws$gcloud]($style)$character"

[character]
error_symbol = "[✗](bold cyan)"
success_symbol = "[❯](bold cyan)"

[directory]
truncation_length = 2
truncation_symbol = "…/"
repo_root_style = "bold cyan"
repo_root_format = "[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "

[git_branch]
format = "[$branch]($style) "
style = "italic cyan"

[git_status]
format     = '[$all_status]($style)'
style      = "cyan"
ahead      = "⇡${count} "
diverged   = "⇕⇡${ahead_count}⇣${behind_count} "
behind     = "⇣${count} "
conflicted = " "
up_to_date = " "
untracked  = "? "
modified   = " "
stashed    = ""
staged     = ""
renamed    = ""
deleted    = ""

[kubernetes]
disabled = false
format = 'on [$symbol $context]($style) '
contexts = [
  { context_pattern = "gke-staging", style = "green", symbol = "" },
  { context_pattern = "gke-prod", style = "red", symbol = "" },
  { context_pattern = "eks-staging", style = "green", symbol = "" },
  { context_pattern = "eks-prod", style = "red", symbol = "" },
  { context_pattern = "tke-staging", style = "green", symbol = "" },
  { context_pattern = "tke-prod", style = "red", symbol = "" },
]

[gcloud]
disabled = true
format = 'on [$symbol ($project)]($style) '
symbol = ''
